cd "D:\tmp\dev\tests\Latinizer"
ren "0лаьвлдфожщцн3км" "0la'vldfozhshchtsn3km"
ren "3філвомфшгуік" "3filvomfshhuik"
ren "івлфдажфдшцугко" "ivlfdazhfdshtsuhko"
ren "вони є" "vony_ie"
ren "Зорбаіфівагукбфівм" "Zorbaifivahukbfivm"
ren "поводж" "povodzh"
ren "Репресивн" "Represyvn"
ren "ф0і84крфолірванцк" "f0i84krfolirvantsk"
ren "фі0уаф0ц9укшфіов" "fi0uaf0ts9ukshfiov"
ren "фіущкшо" "fiushchksho"
ren "фывалорф0льмв" "fyvalorf0l'mv"
cd "D:\tmp\dev\tests\Latinizer\0la'vldfozhshchtsn3km"
ren "жущкшгфіва" "zhushchkshhfiva"
ren "фіадло" "fiadlo"
ren "фівлор" "fivlor"
ren "фофів" "fofiv"
cd "D:\tmp\dev\tests\Latinizer\3filvomfshhuik"
ren "а ти своє" "a_ty_svoie"
ren "вони, міліція, провокує нас" "vony,_militsiia,_provokuie_nas"
ren "покажи" "pokazhy"
ren "тобто це так класно" "tobto_tse_tak_klasno"
ren "які приходять і заявляють" "iaki_prykhodiat'_i_zaiavliaiut'"
cd "D:\tmp\dev\tests\Latinizer\ivlfdazhfdshtsuhko"
ren "ждлфіщшгукьмсл" "zhdlfishchshhuk'msl"
ren "фівадло" "fivadlo"
ren "фівафівдло" "fivafivdlo"
ren "фідвжлоа" "fidvzhloa"
ren "щшгцукдлофіва" "shchshhtsukdlofiva"
cd "D:\tmp\dev\tests\Latinizer\f0i84krfolirvantsk"
ren "Жан-Клод Ван Дам" "Zhan-Klod_Van_Dam"
ren "маю на це право" "maiu_na_tse_pravo"
ren "Скотч, он ведь в хозяйстве незаменим" "Skotch,_on_ved'_v_khoziajstve_nezamenym"
ren "Субстанция" "Substantsyia"
ren "тому що послідовний" "tomu_shcho_poslidovnyj"
ren "Хороший шотландский скотч" "Khoroshyj_shotlandskyj_skotch"
ren "я, як міліціонер" "ia,_iak_militsioner"

